---
- name: Allow Mosh
  ansible.posix.firewalld:
    port: 60000-61000/udp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow IPFS
  ansible.posix.firewalld:
    port: 5001/tcp
    permanent: yes
    state: enabled
    immediate: yes
