---
- name: Install User Tools
  dnf:
    name:
      - tmux
      - mosh
      - urlview
    state: latest

- name: System Tools
  dnf:
    name:
      - dnf-automatic
    state: latest

- name: Webserver
  dnf:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: latest

- name: IPFS Dependencies
  dnf:
    name:
      - nodejs
      - npm
    state: latest
    
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Keep us upgraded
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: yes
