---
- name: Install User Tools
  dnf:
    name:
      - tmux
      - mosh
      - urlview
    state: latest

- name: Webserver
  dnf:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: latest
    
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
