---
- name: DevMicron
  hosts: localhost
  vars:
    service_host: dev.megamicron.net
  tasks:
    - name: setup users
      import_tasks: users.yml
      
    - name: Install Software
      import_tasks: installs.yml
      
    - name: Setup Firewall
      import_tasks: firewall.yml

    - name: Setup Nginx
      import_tasks: nginx.yml
