---
- name: DevMicron
  hosts: localhost
  tasks:
    - name: setup users
      import_tasks: users.yml
      
    - name: Install Software
      import_tasks: installs.yml
      
    - name: Setup Firewall
      import_tasks: firewall.yml